package dao;

import connection.DBConnection;
import model.ReportModel;

import java.sql.*;

public class ReportDao {

    Connection conn = null;
    Statement stmt = null;

    public void saveReport(ReportModel reportModel) {

        int autoGeneratedID;
        try {
            conn = DBConnection.getConnection();
            stmt = conn.createStatement();
            String sql = "insert into reports (id, user_id, type_id, total_score, obtained_score) "
                    + " values ( "
                    + reportModel.getId()
                    + ",'"
                    + reportModel.getUserId()
                    + "','"
                    + reportModel.getTypeId()
                    + "','"
                    + reportModel.getTotalScore()
                    + "','"
                    + reportModel.getObtainedScore()
                    + "')";

            PreparedStatement pstmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
            pstmt.executeUpdate();
            ResultSet keys = pstmt.getGeneratedKeys();
            keys.next();
            autoGeneratedID = keys.getInt(1);
            reportModel.setId(autoGeneratedID);
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            // finally block used to close resources
            try {
                if (stmt != null)
                    conn.close();
            } catch (SQLException se) {
            }// do nothing
            try {
                if (conn != null)
                    conn.close();
            } catch (SQLException se) {
                se.printStackTrace();
            }// end finally try
        }
    }
}